name:                ubootp
version:             1.0.0.0
github:              "voneiden/ubootp"
license:             MIT
author:              "Matti Eiden"
maintainer:          "n/a"
copyright:           "2020 Matti Eiden"

extra-source-files:
- README.md
data-files:
- app/cfg.toml

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Github username here/ubootp#readme>

dependencies:
- base >= 4.7 && < 5
- tomland
- network
- network-multicast
- bytestring
- text
- containers
- ip
- hex-text

library:
  source-dirs: src

executables:
  ubootp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ubootp

tests:
  ubootp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ubootp
